stages:
  - build
  - add-ssh
  - test

build:
  tags: 
    - kvm
    - ubuntu
  stage: build
  variables:
    # set git user in clones to apply patches
    GIT_CLONE_ARGS: '--config user.name="nobody" --config user.email="nobody@example.com"'
    # use cache to clone linux
    KERNEL_CLONE_ARGS: '--reference /home/gitcaches/linux.reference'
    # use cache to clone u-boot
    UBOOT_CLONE_ARGS: '--reference /home/gitcaches/u-boot.reference'
  script:
    # run readme steps
    - tools/10_prepare_host_ubuntu1604.sh
    - sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc-5 /usr/bin/arm-linux-gnueabihf-gcc
    - sudo ln -s /usr/bin/arm-linux-gnueabihf-g++-5 /usr/bin/arm-linux-gnueabihf-g++
    - git config --global user.name "gitlab-runner"
    - git config --global user.email "gitlab-runner@example.com"
    - tools/prepare_uboot.sh v2018.11
    - make uboot-tests
    - make uboot
    - tools/prepare_kernel.sh v4.20
    - make kernel
#    - tools/prepare_etherlab.sh
#    - make etherlab
    # create image instead of writing to device
    - sudo scripts/build_sdimage.sh
  artifacts:
    expire_in: 2 weeks
    paths:
      - sdcard.img

add-ssh:
  tags: 
    - kvm
    - ubuntu
  stage: add-ssh
  script:
    - mkdir mounted_root
    - export SD_LOOPDEVICE=$(sudo losetup --show -Pf sdcard.img)
    - ls -al /dev
    - sudo mount ${SD_LOOPDEVICE}p1 mounted_root
    - sudo mkdir mounted_root/root/.ssh
    - echo ${SSH_AUTHORIZED_KEYS} | sudo tee mounted_root/root/.ssh/authorized_keys
    - sudo chmod 600 mounted_root/root/.ssh/authorized_keys
    - sync && sudo umount mounted_root
  artifacts:
    expire_in: 2 weeks
    paths:
      - sdcard.img
  dependencies:
      - build

test:
  image: ${REGISTRY_HOST}/beckhoff/test_runner:1.2
  tags: 
    - docker
  stage: test
  script:
    - trap 'export real_exit_code=$?; echo "Stopped by trap"; 41_reset_sd.sh ${DEVICE_ID}-${DEVICE};50_power.sh ${DEVICE_ID}-${DEVICE} 0 || true; 99_cleanup.sh || true;  sleep 5 && exit $real_exit_code' SIGINT SIGTERM EXIT
    - source 09_init.sh
    - 50_power.sh ${DEVICE_ID}-${DEVICE} 0
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 40_flash_sd.sh sdcard.img
    - 50_power.sh ${DEVICE_ID}-${DEVICE} 1
    - 51_wait.sh ${DEVICE_ID}-${DEVICE} root
    - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./tests/ root@${TEST_DEVICE_IP}:~/
    - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${TEST_DEVICE_IP} tests/${SCRIPTNAME}.sh
  variables:
    DEVICE: 'CX9020'
    DEVICE_ID: 'CX09'
    SCRIPTNAME: 'test_boot'
  dependencies:
      - add-ssh
  tags:
    - CX09-CX9020
