image: ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}

stages:
  - build-docker-image
  - build
  - test


docker-image:
  image: ${REGISTRY_HOST}/beckhoff/okinak:master
  stage: build-docker-image
  tags:
    - docker
    - privileged
  script: okinak

.build-template: &build-template
  tags: 
    - docker
    - privileged
  stage: build
  artifacts:
    expire_in: 2 weeks
    paths:
      - sdcard.img

build:etherlab:
  <<: *build-template
  script:
    - scripts/run_build.sh

.test-template: &test-template
  image: ${REGISTRY_HOST}/beckhoff/test_stage/test_runner:v4.45
  stage: test
  script:
    - .ci/test_stage.sh
  tags:
    - CX9020

test:etherlab:
  <<: *test-template
  dependencies:
      - build:etherlab

test-manual:etherlab:
  <<: *test-template
  dependencies:
      - build:etherlab
  when: manual
