stages:
  - build

build:
  stage: build
  variables:
    DEBIAN_FRONTEND: 'noninteractive'
    # set git user in clones to apply patches
    GIT_CLONE_ARGS: '--config user.name="nobody" --config user.email="nobody@example.com"'
    # use cache to clone linux
    KERNEL_CLONE_ARGS: '--reference /home/gitcaches/linux-stable-rt.reference'
    # use cache to clone u-boot
    UBOOT_CLONE_ARGS: '--reference /home/gitcaches/u-boot.reference'
  script:
    # run readme steps
    - sudo dpkg --add-architecture i386
    - sudo apt-get update
    # skip questions during package update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y autoconf bc binfmt-support device-tree-compiler gcc-5-arm-linux-gnueabihf git lib32ncurses5-dev lib32stdc++6 lib32z1 libtool make mercurial multistrap qemu qemu-user-static wget xz-utils
    - sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc-5 /usr/bin/arm-linux-gnueabihf-gcc
    - tools/prepare_uboot.sh v2017.01
    - make uboot
    - tools/prepare_kernel.sh v4.4.53-rt66
    - make kernel
    - tools/prepare_etherlab.sh
    - make etherlab
    # create image instead of writing to device
    - sudo scripts/build_sdimage.sh
  artifacts:
    paths:
      - sdcard.img
