stages:
  - build-docker-image
  - build
  - add-ssh
  - test


build-docker-image:
  image: docker:latest
  stage: build-docker-image
  tags:
    - docker
    - privileged
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${REGISTRY_HOST}
    - docker build -t cx9020_builder .
    - docker tag cx9020_builder ${REGISTRY_HOST}/beckhoff/cx9020:latest_builder
    - docker push ${REGISTRY_HOST}/beckhoff/cx9020:latest_builder

build:
  image: ${REGISTRY_HOST}/beckhoff/cx9020:latest_builder
  tags: 
    - docker
    - privileged
  stage: build
  script:
    - scripts/run_build.sh
  artifacts:
    expire_in: 2 weeks
    paths:
      - sdcard.img

add-ssh:
  image: ${REGISTRY_HOST}/beckhoff/cx9020:latest_builder
  tags: 
    - docker
    - privileged
  stage: add-ssh
  script:
    - mkdir mounted_root
    - export SD_LOOPDEVICE=$(sudo losetup --show -Pf sdcard.img)
    - ls -al /dev
    - sudo mount ${SD_LOOPDEVICE}p1 mounted_root
    - sudo mkdir mounted_root/root/.ssh
    - echo ${SSH_AUTHORIZED_KEYS} | sudo tee mounted_root/root/.ssh/authorized_keys
    - sudo chmod 600 mounted_root/root/.ssh/authorized_keys
    - sync && sudo umount mounted_root
  artifacts:
    expire_in: 2 weeks
    paths:
      - sdcard.img
  dependencies:
      - build

test:
  image: ${REGISTRY_HOST}/beckhoff/test_runner:1.2
  stage: test
  script:
    - trap 'export real_exit_code=$?; echo "Stopped by trap"; 41_reset_sd.sh ${DEVICE_ID}-${DEVICE};50_power.sh ${DEVICE_ID}-${DEVICE} 0 || true; 99_cleanup.sh || true;  sleep 5 && exit $real_exit_code' SIGINT SIGTERM EXIT
    - source 09_init.sh
    - 50_power.sh ${DEVICE_ID}-${DEVICE} 0
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 40_flash_sd.sh sdcard.img
    - 50_power.sh ${DEVICE_ID}-${DEVICE} 1
    - 51_wait.sh ${DEVICE_ID}-${DEVICE} root
    - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./tests/ root@${TEST_DEVICE_IP}:~/
    - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${TEST_DEVICE_IP} tests/${SCRIPTNAME}.sh
  variables:
    DEVICE: 'CX9020'
    DEVICE_ID: 'CX09'
    SCRIPTNAME: 'test_boot'
  dependencies:
      - add-ssh
  tags:
    - CX09-CX9020
