stages:
  - build
  - add-ssh
  - test

build:
  tags: 
    - kvm
    - ubuntu
  stage: build
  variables:
    DEBIAN_FRONTEND: 'noninteractive'
    # set git user in clones to apply patches
    GIT_CLONE_ARGS: '--config user.name="nobody" --config user.email="nobody@example.com"'
    # use cache to clone linux
    KERNEL_CLONE_ARGS: '--reference /home/gitcaches/linux-stable-rt.reference'
    # use cache to clone u-boot
    UBOOT_CLONE_ARGS: '--reference /home/gitcaches/u-boot.reference'
  script:
    # run readme steps
    - sudo dpkg --add-architecture i386
    - printf "\ndeb http://ppa.launchpad.net/team-gcc-arm-embedded/ppa/ubuntu xenial main\n" | sudo tee -a /etc/apt/sources.list
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key B4D03348F75E3362B1E1C2A1D1FAA6ECF64D33B0
    - sudo apt-get update
    # skip questions during package update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y autoconf bc binfmt-support device-tree-compiler g++-4.9-arm-linux-gnueabihf gcc-4.9-arm-linux-gnueabihf git lib32ncurses5-dev lib32stdc++6 lib32z1 libtool make mercurial multistrap qemu qemu-user-static wget xz-utils
    - sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc-4.9 /usr/bin/arm-linux-gnueabihf-gcc
    - sudo ln -s /usr/bin/arm-linux-gnueabihf-g++-4.9 /usr/bin/arm-linux-gnueabihf-g++
    - tools/prepare_uboot.sh v2017.07
    - make uboot
    - tools/prepare_kernel.sh v4.9.76-rt61
    - make kernel
    - tools/prepare_etherlab.sh
    - make etherlab
    # create image instead of writing to device
    - sudo scripts/build_sdimage.sh
  artifacts:
    paths:
      - sdcard.img

add-ssh:
  tags: 
    - kvm
    - ubuntu
  stage: add-ssh
  script:
    - mkdir mounted_root
    - export SD_LOOPDEVICE=$(sudo losetup --show -Pf sdcard.img)
    - ls -al /dev
    - sudo mount ${SD_LOOPDEVICE}p1 mounted_root
    - sudo mkdir mounted_root/root/.ssh
    - echo ${SSH_AUTHORIZED_KEYS} | sudo tee mounted_root/root/.ssh/authorized_keys
    - sudo chmod 600 mounted_root/root/.ssh/authorized_keys
    - sync && sudo umount mounted_root
  artifacts:
    paths:
      - sdcard.img
  dependencies:
      - build

test:
  image: ubuntu
  tags: 
    - docker
  stage: test
  script:
    - apt-get update > /dev/null && apt-get install -y openssh-client wget unzip > /dev/null
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -P ${SSH_PORT} sdcard.img ${SSH_USER}@${SSH_HOST}:/tmp/sdcard-${DEVICE}-${CI_BUILD_ID}.img
    - scp -P ${SSH_PORT} tests/${SCRIPTNAME}.sh ${SSH_USER}@${SSH_HOST}:/tmp/${SCRIPTNAME}-${DEVICE}-${CI_BUILD_ID}.sh
    - ssh -p ${SSH_PORT} -t -t ${SSH_USER}@${SSH_HOST} "./61_run_test_sd.sh ${DEVICE_ID}-${DEVICE} /tmp/sdcard-${DEVICE}-${CI_BUILD_ID}.img /tmp/${SCRIPTNAME}-${DEVICE}-${CI_BUILD_ID}.sh ./${SCRIPTNAME}-${DEVICE}-${CI_BUILD_ID}.sh"
  variables:
    DEVICE: 'CX9020'
    DEVICE_ID: 'CX09'
    SCRIPTNAME: 'test_boot'
  dependencies:
      - add-ssh
