name: Build
on: [push]
jobs:
  build-sdcard-image:
    runs-on: ubuntu-latest
    container:
      image: debian:11
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - run: echo hello > sdcard.img
      - name: Archive etherlab image
        uses: actions/upload-artifact@v3
        with:
          name: sdcard-image-etherlab
          path: sdcard.img
          if-no-files-found: error
          retention-days: 2
  release-image:
    needs: build-sdcard-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: ls -alhR .
      - run: gh release create test-ci-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload test-ci-release sdcard-image-etherlab/sdcard.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}