name: Build
on: [push]
jobs:
  build-sdcard-image:
    runs-on: ubuntu-latest
    container:
      image: debian:11
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y sudo gpg
      - run: mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
      - run: tools/10_prepare_host_debian11.sh
      - run: git config --global user.name 'nobody' && git config --global user.email 'nobody@example.org'
      - run: CI_JOB_NAME='build:etherlab' scripts/run_build.sh
      - name: Archive etherlab image
        uses: actions/upload-artifact@v3
        with:
          name: sdcard-image-etherlab
          path: sdcard.img
          if-no-files-found: error
          retention-days: 2
